TenMan.Web/Models/PaymentsByCommittee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TenMan.Web.Data.Entities;

namespace TenMan.Web.Models
{
    public class PaymentsByCommittee
    { 
        public int DebtsCant { get; set; }
        public int PaymentsCant { get; set; }

        public Committee committee { get; set; }
    }
}

TenMan.Web/Models/RequestsReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TenMan.Web.Data.Entities;

namespace TenMan.Web.Models
{
    public class RequestsReportViewModel
    {
        public int TotalCant { get; set; }
        public int InProcessCant { get; set; }
        public int FinishedCant { get; set; }
        public int AsignedCant { get; set; }
        public int GeneratedCant { get; set; }

        public IEnumerable<Request> Requests { get; set; }
    }
}

TenMan.Web/Controllers/ReportsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TenMan.Web.Data;
using TenMan.Web.Data.Entities;
using TenMan.Web.Models;

namespace TenMan.Web.Controllers
{
    public class ReportsController : Controller
    {
        private readonly DataContext _context;

        public ReportsController(DataContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> CommitteeReports()
        {
            return View(await _context.Committees.ToListAsync());
        }
        public IActionResult Expenses()
        {
            return View();
        }
        public IActionResult Bar()
        {
            var markList = GetStudentMarkList();
            return View(markList);
        }
        public IActionResult Line()
        {
            var markList = GetStudentMarkList();
            return View(markList);
        }
        public IActionResult Radar()
        {
            var markList = GetStudentMarkList();
            return View(markList);
        }

        public IActionResult Doughnut()
        {
            var scoreList = GetStudentScoreDetails();
            return View(scoreList);
        }
        public IActionResult Polararea()
        {
            var scoreList = GetStudentScoreDetails();
            return View(scoreList);
        }


        public List<Payment> GetPaymentsList()
        {
            var list = _context.Payments
                .Include(p => p.Unit)
                .ToList();

            return list;
        }
        public IActionResult RequestsReport(int id)
        {
            var committee = _context.Committees.Find(id);

            if (committee == null)
                return NotFound();

            var list = _context.Requests
                .Include(r => r.Unit)
                .ThenInclude(u => u.Committee)
                .Where(r => r.Unit.Committee.Id == id)
                .ToList();

            int generatedCant = 0;
            int asignedCant = 0;
            int finishedCant = 0;
            int inProcessCant = 0;

            foreach (Request item in list)
            {
                if (item.ActualStatus == "Finalizada")
                    finishedCant++;

                else if (item.ActualStatus == "Asignada")
                    asignedCant++;

                else if (item.ActualStatus == "Generada")
                    generatedCant++;

                else
                {
                    inProcessCant++;
                }
            }

            var model = new RequestsReportViewModel
            {
                GeneratedCant = generatedCant,
                AsignedCant = asignedCant,
                FinishedCant = finishedCant,
                InProcessCant = inProcessCant,
                Requests = list
            };
            return View(model);
        }
        //Make function in models and get data from database as per your requirement... //Dont do in controller like this
        public List<StudentMarkDetails> GetStudentMarkList()
        {
            var studentmarkList = new List<StudentMarkDetails>()
            {
                new StudentMarkDetails() { id = 1, name = "Juan", Physics = 62,Chemistry=78,Biology=84,Mathematics=96 },
                new StudentMarkDetails() { id = 2, name = "María", Physics = 96,Chemistry=78,Biology=69,Mathematics=88 },
                new StudentMarkDetails() { id = 3, name = "Barby", Physics = 49,Chemistry=85,Biology=63,Mathematics=77 },
                new StudentMarkDetails() { id = 4, name = "Emilia", Physics = 85,Chemistry=56,Biology=78,Mathematics=55 },
                new StudentMarkDetails() { id = 5, name = "Ainhoa", Physics = 74,Chemistry=55,Biology=36,Mathematics=69 },
            };
            return studentmarkList;
        }
        public List<StudentScoreDetails> GetStudentScoreDetails()
        {
            var studentscoreList = new List<StudentScoreDetails>()
            {
                new StudentScoreDetails() { id = 1, name = "Juan", score = 62},
                new StudentScoreDetails() { id = 2, name = "María", score = 96 },
                new StudentScoreDetails() { id = 3, name = "Barby", score = 49 },
                new StudentScoreDetails() { id = 4, name = "Emilia", score = 85 },
                new StudentScoreDetails() { id = 5, name = "Ainhoa", score = 74},
            };
            return studentscoreList;
        }

    }
}

TenMan.Web/Views/Reports/Bar.cshtml
@model List<StudentMarkDetails>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h4 class="display-4">Students Mark Details By Bar Chart</h4>
    <h3><a href="~/Home/Index">Back</a></h3>
    <div class="card">
        <div class="card-header">
            <div class="chart">
                <canvas id="barchart"></canvas>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
<script>
    var barCanvas = document.getElementById("barchart");
    var Physics = [];//these are all javascript array variables
    var Chemistry = [];
    var Biology = [];
    var Mathematics = [];

    @if(Model.Count>0)
    {
        foreach(var item in Model)
        {
            @:Physics.push(@item.Physics);
            @:Chemistry.push(@item.Chemistry);
            @:Biology.push(@item.Biology);
            @:Mathematics.push(@item.Mathematics);
        }
    }
    var Physics = {
        label: 'Physics',
        data: Physics,
        backgroundColor: 'rgb(255, 99, 132)',
        borderWidth: 0,
        lineTension: 0,
    };
    var Chemistry = {
        label: 'Chemistry',
        data: Chemistry,
        backgroundColor: 'rgb(54, 162, 235)',
        borderWidth: 0,
    };
    var Biology = {
        label: 'Biology',
        data: Biology,
        backgroundColor: 'rgb(157, 230, 41)',
        borderWidth: 0,
    };
    var Mathematics = {
        label: 'Mathematics',
        data: Mathematics,
        backgroundColor: 'rgb(41, 224, 230)',
        borderWidth: 0,
    };
    var datasetvalues = {
        labels: ["John", "Mary", "Asha", "Emily", "Bonnie"],//x-axis label values
        datasets: [Physics, Chemistry, Biology, Mathematics]//y-axis
    };
    var chartOptions = {
        scales: {
            xAxes: [{
                barPercentage: 1,//Percent (0-1) of the available width each bar should
                categoryPercentage: 0.6,//Percent (0-1) of the available width each category
            }],
            yAxes: [{
                barPercentage: 1,
                categoryPercentage: 0.6,
                ticks: {
                    beginAtZero: true
                }
            }],
        }
    };
    var barChart = new Chart(barCanvas, {
        type: 'bar',
        data: datasetvalues,
        options: chartOptions
    });
</script>

TenMan.Web/Views/Reports/CommitteeReports.cshtml
@model IEnumerable<TenMan.Web.Data.Entities.Committee>

@{
    ViewData["Title"] = "Lista de Consorcios";
}

<h2>Consorcios</h2>

<table class="table table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Neighborhood)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Neighborhood)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <a asp-controller="Reports" asp-action="RequestsReport" class="btn btn-warning" asp-route-id="@item.Id">Solicitudes</a> |
                    @*<a asp-action="Details" class="btn btn-info" asp-route-id="@item.Id">Detalles</a> |
                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Eliminar</a>*@
                </td>
            </tr>
        }
    </tbody>
</table>

TenMan.Web/Views/Reports/Doughnut.cshtml
@model List<StudentScoreDetails>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h4 class="display-4">Students Score Details By Doughnut Chart</h4>
    <h3><a href="~/Home/Index">Back</a></h3>
    <div class="card">
        <div class="card-header">
            <div class="chart">
                <canvas id="doughnutchart"></canvas>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
<script>
    var doughnutchartCanvas = document.getElementById("doughnutchart");
         var studentname = [];
     var score = [];
    @if(Model.Count>0)
    {
        foreach(var item in Model)
        {
            @:studentname.push('@item.name');
            @:score.push(@item.score);
        }
    }
    var doughnutChart = new Chart(doughnutchartCanvas, {
        type: 'doughnut',
        data: {
            labels: studentname,
        datasets: [{
            data: score,
            borderWidth: 0,
            backgroundColor: [
                'rgb(255, 99, 132)',
                'rgb(54, 162, 235)',
                'rgb(157, 230, 41)',
                'rgb(41, 224, 230)',
                'rgb(255, 255, 0)'
            ],
            hoverBackgroundColor: [
                'rgb(255, 99, 132)',
                'rgb(54, 162, 235)',
                'rgb(157, 230, 41)',
                'rgb(41, 224, 230)',
                'rgb(255, 255, 0)'
            ]
        }]
    },
        options: {
            responsive:true,
            legend: {
                position: "bottom",
                labels: {
                    boxWidth: 11,
                    fontColor: "#757681",
                    fontSize: 11
                }
            }
        }
    });
</script>

TenMan.Web/Views/Reports/Expenses.cshtml
@model List<StudentMarkDetails>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h4 class="display-4">Students Mark Details By Bar Chart</h4>
    <h3><a href="~/Home/Index">Back</a></h3>
    <div class="card">
        <div class="card-header">
            <div class="chart">
                <canvas id="barchart"></canvas>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
<script>
    var barCanvas = document.getElementById("barchart");
    var Physics = [];//these are all javascript array variables
    var Chemistry = [];
    var Biology = [];
    var Mathematics = [];

    @if(Model.Count>0)
    {
        foreach(var item in Model)
        {
            @:Physics.push(@item.Physics);
            @:Chemistry.push(@item.Chemistry);
            @:Biology.push(@item.Biology);
            @:Mathematics.push(@item.Mathematics);
        }
    }
    var Physics = {
        label: 'Physics',
        data: Physics,
        backgroundColor: 'rgb(255, 99, 132)',
        borderWidth: 0,
        lineTension: 0,
    };
    var Chemistry = {
        label: 'Chemistry',
        data: Chemistry,
        backgroundColor: 'rgb(54, 162, 235)',
        borderWidth: 0,
    };
    var Biology = {
        label: 'Biology',
        data: Biology,
        backgroundColor: 'rgb(157, 230, 41)',
        borderWidth: 0,
    };
    var Mathematics = {
        label: 'Mathematics',
        data: Mathematics,
        backgroundColor: 'rgb(41, 224, 230)',
        borderWidth: 0,
    };
    var datasetvalues = {
        labels: ["John", "Mary", "Asha", "Emily", "Bonnie"],//x-axis label values
        datasets: [Physics, Chemistry, Biology, Mathematics]//y-axis
    };
    var chartOptions = {
        scales: {
            xAxes: [{
                barPercentage: 1,//Percent (0-1) of the available width each bar should
                categoryPercentage: 0.6,//Percent (0-1) of the available width each category
            }],
            yAxes: [{
                barPercentage: 1,
                categoryPercentage: 0.6,
                ticks: {
                    beginAtZero: true
                }
            }],
        }
    };
    var barChart = new Chart(barCanvas, {
        type: 'bar',
        data: datasetvalues,
        options: chartOptions
    });
</script>

TenMan.Web/Views/Reports/PaymentsBar.cshtml
@model List<StudentMarkDetails>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h4 class="display-4">Pagos</h4>
    <h3><a href="~/Home/Index">Volver</a></h3>
    <div class="card">
        <div class="card-header">
            <div class="chart">
                <canvas id="barchart"></canvas>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
<script>
    var barCanvas = document.getElementById("barchart");
    var Physics = [];//these are all javascript array variables
    var Chemistry = [];
    var Biology = [];
    var Mathematics = [];

    @if(Model.Count>0)
    {
        foreach(var item in Model)
        {
            @:Physics.push(@item.);
            @:Chemistry.push(@item.Chemistry);
            @:Biology.push(@item.Biology);
            @:Mathematics.push(@item.Mathematics);
        }
    }
    var Physics = {
        label: 'Physics',
        data: Physics,
        backgroundColor: 'rgb(255, 99, 132)',
        borderWidth: 0,
        lineTension: 0,
    };
    var Chemistry = {
        label: 'Chemistry',
        data: Chemistry,
        backgroundColor: 'rgb(54, 162, 235)',
        borderWidth: 0,
    };
    var Biology = {
        label: 'Biology',
        data: Biology,
        backgroundColor: 'rgb(157, 230, 41)',
        borderWidth: 0,
    };
    var Mathematics = {
        label: 'Mathematics',
        data: Mathematics,
        backgroundColor: 'rgb(41, 224, 230)',
        borderWidth: 0,
    };
    var datasetvalues = {
        labels: ["John", "Mary", "Asha", "Emily", "Bonnie"],//x-axis label values
        datasets: [Physics, Chemistry, Biology, Mathematics]//y-axis
    };
    var chartOptions = {
        scales: {
            xAxes: [{
                barPercentage: 1,//Percent (0-1) of the available width each bar should
                categoryPercentage: 0.6,//Percent (0-1) of the available width each category
            }],
            yAxes: [{
                barPercentage: 1,
                categoryPercentage: 0.6,
                ticks: {
                    beginAtZero: true
                }
            }],
        }
    };
    var barChart = new Chart(barCanvas, {
        type: 'bar',
        data: datasetvalues,
        options: chartOptions
    });
</script>

TenMan.Web/Views/Reports/PaymentsByCommittee.cshtml
@model List<PaymentsByCommittee>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h4 class="display-4">Students Mark Details By Bar Chart</h4>
    <h3><a href="~/Home/Index">Back</a></h3>
    <div class="card">
        <div class="card-header">
            <div class="chart">
                <canvas id="barchart"></canvas>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
<script>
    var barCanvas = document.getElementById("barchart");
    var Debts = [];//these are all javascript array variables
    var Payments = [];

    @if(Model.Count>0)
    {
        foreach(var item in Model)
        {
            @:Payments.push(@item.PaymentsCant);
            @:Debts.push(@item.DebtsCant);
        }
    }
    var Debts = {
        label: 'Adeudados',
        data: Debts,
        backgroundColor: 'rgb(255, 99, 132)',
        borderWidth: 0,
        lineTension: 0,
    };
    var Payments = {
        label: 'Pagos',
        data: Payments,
        backgroundColor: 'rgb(54, 162, 235)',
        borderWidth: 0,
    };
    var datasetvalues = {
        labels: [Debts, Payments],//x-axis label values
        datasets: [Debts, Payments]//y-axis
    };
    var chartOptions = {
        scales: {
            xAxes: [{
                barPercentage: 1,//Percent (0-1) of the available width each bar should
                categoryPercentage: 0.6,//Percent (0-1) of the available width each category
            }],
            yAxes: [{
                barPercentage: 1,
                categoryPercentage: 0.6,
                ticks: {
                    beginAtZero: true
                }
            }],
        }
    };
    var barChart = new Chart(barCanvas, {
        type: 'bar',
        data: datasetvalues,
        options: chartOptions
    });
</script>

TenMan.Web/Views/Reports/RequestsReport.cshtml
@model RequestsReportViewModel
@{
    ViewData["Title"] = "Reporte de Solicitudes";
}

<div class="text-center">
    <h4 class="display-4">Cantidad de solicitudes por Estado</h4>
    <h3><a href="~/Home/Index" class="btn btn-success">Volver</a></h3>
    <div class="card">
        <div class="card-header">
            <div class="chart">
                <canvas id="doughnutchart"></canvas>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
<script>
    var doughnutchartCanvas = document.getElementById("doughnutchart");
    var inprocess = [];
    var generated = [];
    var asigned = [];
    var finished = [];

    var doughnutChart = new Chart(doughnutchartCanvas, {
        type: 'doughnut',
        data: {
            labels: ['Generada', 'En Proceso', 'Asignada', 'Finalizada'],
        datasets: [{
            data: [@Model.GeneratedCant,@Model.InProcessCant,@Model.AsignedCant,@Model.FinishedCant],
            borderWidth: 0,
            backgroundColor: [
                'rgb(255, 99, 132)',
                'rgb(54, 162, 235)',
                'rgb(157, 230, 41)',
                'rgb(41, 224, 230)',
                'rgb(255, 255, 0)'
            ],
            hoverBackgroundColor: [
                'rgb(255, 99, 132)',
                'rgb(54, 162, 235)',
                'rgb(157, 230, 41)',
                'rgb(41, 224, 230)',
                'rgb(255, 255, 0)'
            ]
        }]
    },
        options: {
            responsive:true,
            legend: {
                position: "bottom",
                labels: {
                    boxWidth: 11,
                    fontColor: "#757681",
                    fontSize: 11
                }
            }
        }
    });
</script>